name: rickandmorty
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.1
  dio_smart_retry: ^7.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  intl: ^0.19.0
  number_paginator: ^0.4.3
  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
